# Copyright 2016, 2017 Peter Dimov
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

language: cpp

sudo: false

python: "2.7"

os:
  - linux
  - osx

branches:
  only:
    - master
    - develop

env:
  matrix:
    - BOGUS_JOB=true

matrix:

  exclude:
    - env: BOGUS_JOB=true

  include:
    - os: linux
      env: TOOLSET=gcc COMPILER=g++ CXXSTD=c++17
      arch: arm64

install:
  - cd ..
  - git clone -b $TRAVIS_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule update --init tools/build
  - git submodule update --init libs/detail
  - git submodule update --init libs/core
  - git submodule update --init libs/assert
  - git submodule update --init libs/type_traits
  - cp -r $TRAVIS_BUILD_DIR/* libs/config
  - ./bootstrap.sh
  - ./b2 headers
 
script:
  - |-
    echo "using $TOOLSET : : $COMPILER : <cxxflags>-std=$CXXSTD ;" > ~/user-config.jam
  - (cd libs/config/test && ../../../b2 print_config_info toolset=$TOOLSET && ./config_info_travis)
  - ./b2 -j3 libs/config/test toolset=$TOOLSET

notifications:
  email:
    on_success: always